// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlY2xzQ3JQ1U1KtQPBjf3HC69jCRd3sBQ',
    appId: '1:13849478066:web:856d51edf33f4c64159aab',
    messagingSenderId: '13849478066',
    projectId: 'int3120-memrize',
    authDomain: 'int3120-memrize.firebaseapp.com',
    storageBucket: 'int3120-memrize.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz_OXgjoXl4v1vRVE2w1FEY_txKlhhL7s',
    appId: '1:13849478066:android:e0b25b6c9182484a159aab',
    messagingSenderId: '13849478066',
    projectId: 'int3120-memrize',
    storageBucket: 'int3120-memrize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb66gk_OTd245fuXgjKClML38bcnZsD9k',
    appId: '1:13849478066:ios:717b50c784c25dac159aab',
    messagingSenderId: '13849478066',
    projectId: 'int3120-memrize',
    storageBucket: 'int3120-memrize.appspot.com',
    iosClientId: '13849478066-k587u0mn2784l2sso9tt941i43sedshq.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb66gk_OTd245fuXgjKClML38bcnZsD9k',
    appId: '1:13849478066:ios:717b50c784c25dac159aab',
    messagingSenderId: '13849478066',
    projectId: 'int3120-memrize',
    storageBucket: 'int3120-memrize.appspot.com',
    iosClientId: '13849478066-k587u0mn2784l2sso9tt941i43sedshq.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
