name: Test

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level:
          - 29
      fail-fast: true
    environment: duongoku

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'master'
          
      - name: Create .env file
        run: |
          touch .env
          echo "SUPABASE_URL=\"${{ secrets.SUPABASE_URL }}\"" >> .env
          echo "SUPABASE_ANON_KEY=\"${{ secrets.SUPABASE_ANON_KEY }}\"" >> .env
          echo "TEST_EMAIL=\"${{ secrets.TEST_EMAIL }}\"" >> .env
          echo "TEST_PASSWORD=\"${{ secrets.TEST_PASSWORD }}\"" >> .env
          cat .env

      - name: Install dependencies
        run: flutter pub get
      
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      
