name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'master'

      - name: Install dependencies
        run: flutter pub get
        
      - name: Analyze source code with flutter analyzer
        run: flutter analyze

      - name: Analyze source code with dart_code_metrics
        run: flutter pub run dart_code_metrics:metrics --reporter=github lib
      
