name: Lint

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          envkey_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          envkey_TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          envkey_TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          fail_on_empty: false
        
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'master'

      - name: Install dependencies
        run: flutter pub get
        
      - name: Analyze source code with flutter analyzer
        run: flutter analyze

      - name: Analyze source code with dart_code_metrics
        run: flutter pub run dart_code_metrics:metrics --reporter=github lib
      
